module.exports = function padronizarDadosAnimal(animal = {}) {
  return {
    id: animal.id || null,
    numero: animal.numero || '',
    brinco: animal.brinco || '',
    nascimento: animal.nascimento || '',
    sexo: animal.sexo || '',
    idade: animal.idade || '',
    categoria: animal.categoria || '',
    origem: animal.origem || '',
    raca: animal.raca || '',
    grupo: animal.grupo || '',
    status: animal.status || 'ativo',
    dataSaida: animal.dataSaida || null,
    motivoSaida: animal.motivoSaida || '',
    observacaoSaida: animal.observacaoSaida || '',
    valorVenda: animal.valorVenda || null,
    pai: animal.pai || '',
    mae: animal.mae || '',
    partos: animal.partos || [],
    numeroPartos: animal.numeroPartos || 0,
    nLactacoes: animal.nLactacoes || 0,
    ultimaIA: animal.ultimaIA || '',
    ultimoParto: animal.ultimoParto || '',
    lactacoes: animal.lactacoes || [],
    tratamentos: animal.tratamentos || [],
    ocorrencias: animal.ocorrencias || [],
    pesagens: animal.pesagens || [],
    producaoLeite: animal.producaoLeite || [],
    checklistVermifugado: animal.checklistVermifugado || false,
    checklistGrupoDefinido: animal.checklistGrupoDefinido || false,
    fichaComplementarOK: animal.fichaComplementarOK || false,
    del: animal.del || 0,
    descartado: animal.descartado || false,
  };
};
